#@ load("@ytt:data", "data")

#@ def labels():
app: spring-petclinic
#@ end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: spring-petclinic
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: spring-petclinic
        image: springcommunity/spring-framework-petclinic
        ports:
        - name: http
          containerPort: #@ data.values.app_port
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: spring-petclinic
  labels: #@ labels()
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: http
  selector: #@ labels()
